### ISSUE TITLE
flag if connection had issues

### ISSUE THREAD

**Issue by mzealey** [DNSFilter/dns-multiplex#4]
Can you provide a way for us to poll the `Conn` to see if the connection is currently broken (ie we know we cannot connect to the server) ?

**Comment by mzealey** [comment]
@zserge I see the commit, however it is not quite according to the spec above - it should only happen if/when we know we cannot establish connection at the moment.

**Comment by zserge** [comment]
Changed Alive() to Broken(), now it's true when Dial failed at least once, and false if Dial succeeded last time.
